import type { Watch, WatchCategory } from './types';

export const WATCH_CATEGORIES: WatchCategory[] = ["Vanguarda", "Clássicos Reinventados", "Estruturais"];

export const WATCHES: Watch[] = [
    { id: 1, name: "Ocular", category: "Vanguarda", imageUrl: "https://i.imgur.com/Fwqp0pG.png", description: "Uma janela para a alma do tempo." },
    { id: 2, name: "Singularidade", category: "Vanguarda", imageUrl: "https://i.imgur.com/jkTHOo7.png", description: "Onde o tempo colapsa e renasce." },
    { id: 3, name: "Axioma", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/dDIbN6J.png", description: "A verdade fundamental da elegância." },
    { id: 4, name: "Órbita", category: "Vanguarda", imageUrl: "https://i.imgur.com/Z4c5fWV.png", description: "Movimento perpétuo em seu pulso." },
    { id: 5, name: "Nexus", category: "Estruturais", imageUrl: "https://i.imgur.com/2dB8NiY.png", description: "A conexão entre forma e função." },
    { id: 6, name: "Crono-Geometria", category: "Estruturais", imageUrl: "https://i.imgur.com/7DODHrU.png", description: "As formas do tempo, reveladas." },
    { id: 7, name: "Paradoxo", category: "Vanguarda", imageUrl: "https://i.imgur.com/opzy5pF.png", description: "Contradição que define a perfeição." },
    { id: 8, name: "Legado", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/s0iIfAP.png", description: "O passado, redesenhado para o futuro." },
    { id: 9, name: "Vértice", category: "Estruturais", imageUrl: "https://i.imgur.com/HGHZxks.png", description: "O ponto mais alto da engenharia." },
    { id: 10, name: "Ressonância", category: "Vanguarda", imageUrl: "https://i.imgur.com/6jHAirX.png", description: "Vibrações do futuro, hoje." },
    { id: 11, name: "Matriz", category: "Estruturais", imageUrl: "https://i.imgur.com/uczomEz.png", description: "A estrutura fundamental do tempo." },
    { id: 12, name: "Eternidade", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/RezTdNM.png", description: "Um clássico que nunca se desvanece." },
    { id: 13, name: "Quasar", category: "Vanguarda", imageUrl: "https://i.imgur.com/u8Risnx.png", description: "Brilho que transcende galáxias." },
    { id: 14, name: "Relíquia", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/ANqc9pa.png", description: "Um tesouro redescoberto." },
    { id: 15, name: "Horizonte", category: "Vanguarda", imageUrl: "https://i.imgur.com/RTAMOzV.png", description: "O limite entre o conhecido e o inexplorado." },
    { id: 16, name: "Fatum", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/3jGDWAJ.png", description: "O destino forjado em aço e tempo." },
    { id: 17, name: "Aethelred", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/E2Za9XK.png", description: "Nobreza e precisão em cada detalhe." },
    { id: 18, name: "Cosmos", category: "Vanguarda", imageUrl: "https://i.imgur.com/tsujh5C.png", description: "O universo contido em um mostrador." },
    { id: 19, name: "Magnus", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/CDtBuiC.png", description: "A grandeza de um design atemporal." },
    { id: 20, name: "Ícaro", category: "Vanguarda", imageUrl: "https://i.imgur.com/Bdv6uQ8.png", description: "Ousadia que toca o sol." },
    { id: 21, name: "Orion", category: "Estruturais", imageUrl: "https://i.imgur.com/lyYkBWM.png", description: "Uma constelação de engenharia." },
    { id: 22, name: "Titã", category: "Estruturais", imageUrl: "https://i.imgur.com/Bl8zQVx.png", description: "Força e poder em forma de relógio." },
    { id: 23, name: "Soberano", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/L85vEAX.png", description: "O poder da elegância clássica." },
    { id: 24, name: "Odisseia", category: "Vanguarda", imageUrl: "https://i.imgur.com/dTcaK3H.png", description: "Uma jornada através do tempo." },
    { id: 25, name: "Arcano", category: "Vanguarda", imageUrl: "https://i.imgur.com/8BhOFtt.png", description: "Segredos do tempo revelados." },
    { id: 26, name: "Centurion", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/OFtlbhq.png", description: "Comando e disciplina no pulso." },
    { id: 27, name: "Gênese", category: "Estruturais", imageUrl: "https://i.imgur.com/GGX93mQ.png", description: "O início de uma nova era na horologia." },
    { id: 28, name: "Chrono", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/Sr76ElE.png", description: "A essência do tempo, capturada." },
    { id: 29, name: "Vórtice", category: "Vanguarda", imageUrl: "https://i.imgur.com/9MoIgPd.png", description: "Atraído para o centro do tempo." },
    { id: 30, name: "Monolito", category: "Estruturais", imageUrl: "https://i.imgur.com/1Qf1djs.png", description: "Presença imponente e design puro." },
    { id: 31, name: "Aura", category: "Vanguarda", imageUrl: "https://i.imgur.com/ycDfqCK.png", description: "A energia do tempo, visível." },
    { id: 32, name: "Equilíbrio", category: "Estruturais", imageUrl: "https://i.imgur.com/q5Rglrh.png", description: "Harmonia perfeita entre componentes." },
    { id: 33, name: "Pulsar", category: "Vanguarda", imageUrl: "https://i.imgur.com/9AHz4BH.png", description: "O batimento cardíaco do cosmos." },
    { id: 34, name: "Kairo", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/OY77Hmy.png", description: "O momento oportuno, eternizado." },
    { id: 35, name: "Tempus", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/jRPGgso.png", description: "A forma clássica do tempo." },
    { id: 36, name: "Fluxo", category: "Vanguarda", imageUrl: "https://i.imgur.com/3ssU8Ai.png", description: "O movimento contínuo do tempo." },
    { id: 37, name: "Apex", category: "Estruturais", imageUrl: "https://i.imgur.com/6aqjGO7.png", description: "O auge da engenharia relojoeira." },
    { id: 38, name: "Cifra", category: "Vanguarda", imageUrl: "https://i.imgur.com/hOY5hIr.png", description: "Decifre os códigos do tempo." },
    { id: 39, name: "Vesper", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/8ZUDrla.png", description: "A elegância da noite." },
    { id: 40, name: "Fragmento", category: "Estruturais", imageUrl: "https://i.imgur.com/fs54tLW.png", description: "Uma parte do todo, em perfeição." },
    { id: 41, name: "Axius", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/rfTQFA0.png", description: "O eixo da elegância atemporal." },
    { id: 42, name: "Cortex", category: "Estruturais", imageUrl: "https://i.imgur.com/KH2OIPL.png", description: "A inteligência por trás do design." },
    { id: 43, name: "Momentum", category: "Vanguarda", imageUrl: "https://i.imgur.com/wk77AK6.png", description: "O ímpeto do futuro." },
    { id: 44, name: "Espectro", category: "Vanguarda", imageUrl: "https://i.imgur.com/72IiUhs.png", description: "Todas as facetas do tempo." },
    { id: 45, name: "Época", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/5Gyp1nW.png", description: "Marcando uma era de estilo." },
    { id: 46, name: "Quantum", category: "Vanguarda", imageUrl: "https://i.imgur.com/ElxWIze.png", description: "A menor partícula do tempo, magnificada." },
    { id: 47, name: "Nébula", category: "Vanguarda", imageUrl: "https://i.imgur.com/L8BawnQ.png", description: "Onde o tempo e o espaço se encontram." },
    { id: 48, name: "Virtuoso", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/ObNRUwk.png", description: "Maestria em cada detalhe." },
    { id: 49, name: "Mecanismo", category: "Estruturais", imageUrl: "https://i.imgur.com/cTRGwm1.png", description: "A alma da máquina, exposta." },
    { id: 50, name: "Imperium", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/5yZyKH9.png", description: "O comando absoluto do tempo." },
    { id: 51, name: "Antimatéria", category: "Vanguarda", imageUrl: "https://i.imgur.com/bpjHbU5.png", description: "O tempo em sua forma mais enigmática." },
    { id: 52, name: "Caleidoscópio", category: "Vanguarda", imageUrl: "https://i.imgur.com/N0dWJmd.png", description: "Múltiplas facetas do tempo em movimento." },
    { id: 53, name: "Vanguarda", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/Meh9XLb.png", description: "Liderando o caminho com elegância." },
    { id: 54, name: "Alquimia", category: "Vanguarda", imageUrl: "https://i.imgur.com/NVxE69m.png", description: "Transformando o tempo em arte." },
    { id: 55, name: "Sentinela", category: "Estruturais", imageUrl: "https://i.imgur.com/PAHDhv4.png", description: "O guardião vigilante do tempo." },
    { id: 56, name: "Fóton", category: "Vanguarda", imageUrl: "https://i.imgur.com/89OIKbs.png", description: "A velocidade da luz no seu pulso." },
    { id: 57, name: "Obsidiana", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/fthNwZi.png", description: "Elegância profunda e atemporal." },
    { id: 58, name: "Zênite", category: "Estruturais", imageUrl: "https://i.imgur.com/nRICm9x.png", description: "O ponto mais alto da precisão." },
    { id: 59, name: "Andrômeda", category: "Vanguarda", imageUrl: "https://i.imgur.com/q9rhBrY.png", description: "Uma galáxia de possibilidades." },
    { id: 60, name: "Aurum", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/eRqi97V.png", description: "A perfeição do ouro, reinventada." },
    { id: 61, name: "Reactor", category: "Estruturais", imageUrl: "https://i.imgur.com/8OK8Xrp.png", description: "O núcleo de energia do tempo." },
    { id: 62, name: "Mirage", category: "Vanguarda", imageUrl: "https://i.imgur.com/cNVmjG1.png", description: "Uma ilusão de tempo, tornada real." },
    { id: 63, name: "Peregrino", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/jvuP5QQ.png", description: "Uma jornada atemporal de estilo." },
    { id: 64, name: "Catalisador", category: "Estruturais", imageUrl: "https://i.imgur.com/YXr8slg.png", description: "Acelerando o futuro da horologia." },
    { id: 65, name: "Eclipse", category: "Vanguarda", imageUrl: "https://i.imgur.com/xbaWRUQ.png", description: "Onde a luz e a sombra do tempo se encontram." },
    { id: 66, name: "Protocolo", category: "Estruturais", imageUrl: "https://i.imgur.com/bqoXJj9.png", description: "As regras da precisão, reescritas." },
    { id: 67, name: "Saga", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/bM9nlGq.png", description: "Uma história de elegância contada no tempo." },
    { id: 68, name: "Éter", category: "Vanguarda", imageUrl: "https://i.imgur.com/1RsZxSQ.png", description: "O elemento intangível do tempo." },
    { id: 69, name: "Aristocrata", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/p90HaCy.png", description: "Nobreza e distinção em cada segundo." },
    { id: 70, name: "Hiperion", category: "Vanguarda", imageUrl: "https://i.imgur.com/3Zf1CFF.png", description: "Um titã do tempo, nascido da luz." },
    { id: 71, name: "Axioma II", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/NlWSmtT.png", description: "A evolução da verdade fundamental." },
    { id: 72, name: "Cripto", category: "Vanguarda", imageUrl: "https://i.imgur.com/YctaJtx.png", description: "O tempo em sua forma mais enigmática e segura." },
    { id: 73, name: "Engrama", category: "Estruturais", imageUrl: "https://i.imgur.com/Cp8SdMG.png", description: "A memória física do tempo." },
    { id: 74, name: "Íon", category: "Vanguarda", imageUrl: "https://i.imgur.com/TvWddDJ.png", description: "Uma carga de energia positiva no tempo." },
    { id: 75, name: "Nauta", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/rTXdjdl.png", description: "Navegando as correntes do tempo com estilo." },
    { id: 76, name: "Glifo", category: "Vanguarda", imageUrl: "https://i.imgur.com/rJ6UVQh.png", description: "Símbolos arcanos que marcam o tempo." },
    { id: 77, name: "Autômato", category: "Estruturais", imageUrl: "https://i.imgur.com/p3ZLu6n.png", description: "A beleza da máquina em movimento perpétuo." },
    { id: 78, name: "Aetherium", category: "Vanguarda", imageUrl: "https://i.imgur.com/UN2oYcZ.png", description: "A essência etérea do tempo, cristalizada." },
    { id: 79, name: "Valquíria", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/5DSevPE.png", description: "Força e elegância em batalha com o tempo." },
    { id: 80, name: "Colosso", category: "Estruturais", imageUrl: "https://i.imgur.com/RM3hTFY.png", description: "Uma estrutura monumental de tempo e aço." },
    { id: 81, name: "Oráculo", category: "Vanguarda", imageUrl: "https://i.imgur.com/oZIDk8G.png", description: "Vislumbres do futuro em seu pulso." },
    { id: 82, name: "Nomos", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/BJiJkDa.png", description: "A lei da elegância, personificada." },
    { id: 83, name: "Exoesqueleto", category: "Estruturais", imageUrl: "https://i.imgur.com/0PJeLP5.png", description: "A estrutura externa da perfeição." },
    { id: 84, name: "Cronosfera", category: "Vanguarda", imageUrl: "https://i.imgur.com/fScncKo.png", description: "Uma esfera de tempo, perfeitamente contida." },
    { id: 85, name: "Herdeiro", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/6SKhrLr.png", description: "O legado da tradição, para a nova geração." },
    { id: 86, name: "Fractal", category: "Estruturais", imageUrl: "https://i.imgur.com/UAxS8r8.png", description: "Padrões infinitos na geometria do tempo." },
    { id: 87, name: "Eon", category: "Vanguarda", imageUrl: "https://i.imgur.com/IrR67YP.png", description: "Uma era de inovação no seu pulso." },
    { id: 89, name: "Leviatã", category: "Estruturais", imageUrl: "https://i.imgur.com/LXEsTEB.png", description: "A força monumental das profundezas do tempo." },
    { id: 90, name: "Galileo", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/00l2X3P.png", description: "Observando as estrelas, contando o tempo." },
    { id: 91, name: "Cíclope", category: "Vanguarda", imageUrl: "https://i.imgur.com/4GfGnnd.png", description: "Um único olhar para o futuro do tempo." },
    { id: 92, name: "Arquétipo", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/tLhghwW.png", description: "O modelo original da perfeição." },
    { id: 93, name: "Tesseract", category: "Estruturais", imageUrl: "https://i.imgur.com/6SynKP3.png", description: "A quarta dimensão, visível no tempo." },
    { id: 94, name: "Fênix", category: "Vanguarda", imageUrl: "https://i.imgur.com/d8VaqOP.png", description: "Renasce a cada segundo, mais forte." },
    { id: 95, name: "Legionário", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/ETM2WDf.png", description: "A disciplina do tempo, em formação." },
    { id: 96, name: "Astromecânico", category: "Estruturais", imageUrl: "https://i.imgur.com/PzZ4Odc.png", description: "A mecânica celeste no seu pulso." },
    { id: 97, name: "Quimera", category: "Vanguarda", imageUrl: "https://i.imgur.com/jvOVMAy.png", description: "Uma fusão mítica de design e função." },
    { id: 98, name: "Precursor", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/3ThQRSI.png", description: "Aquele que veio antes, para definir o futuro." },
    { id: 99, name: "Sincronia", category: "Estruturais", imageUrl: "https://i.imgur.com/zLJVWbM.png", description: "A perfeita harmonia entre as partes." },
    { id: 100, name: "Supernova", category: "Vanguarda", imageUrl: "https://i.imgur.com/2yWBboT.png", description: "Uma explosão de brilho que marca o tempo." },
    { id: 101, name: "Hiperestrutura", category: "Vanguarda", imageUrl: "https://i.imgur.com/99b48Z9.png", description: "A complexidade arquitetônica do futuro." },
    { id: 102, name: "Aeronauta", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/YwHZuVY.png", description: "Navegando os céus do tempo com precisão." },
    { id: 103, name: "Abismo", category: "Vanguarda", imageUrl: "https://i.imgur.com/JyLFeJQ.png", description: "Um mergulho nas profundezas desconhecidas do tempo." },
    { id: 104, name: "Monarca", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/kC2c7iw.png", description: "A soberania do design clássico e imponente." },
    { id: 105, name: "Orbe", category: "Vanguarda", imageUrl: "https://i.imgur.com/CvE85WD.png", description: "Uma esfera perfeita que contém o tempo." },
    { id: 106, name: "Autarca", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/L9OlDQO.png", description: "Governa o tempo com autoridade e estilo." },
    { id: 107, name: "Cinético", category: "Estruturais", imageUrl: "https://i.imgur.com/FZB0leO.png", description: "A energia do movimento, capturada." },
    { id: 108, name: "Paradigma", category: "Vanguarda", imageUrl: "https://i.imgur.com/OUQMMxu.png", description: "Um novo modelo para a medição do tempo." },
    { id: 109, name: "Célula", category: "Estruturais", imageUrl: "https://i.imgur.com/drxLIwW.png", description: "A unidade básica da complexidade do tempo." },
    { id: 110, name: "Nadir", category: "Vanguarda", imageUrl: "https://i.imgur.com/s66A9pm.png", description: "O ponto mais profundo da inovação temporal." },
    { id: 111, name: "Regente", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/SsAIPQ9.png", description: "A autoridade do estilo clássico, redefinida." },
    { id: 112, name: "Singular", category: "Vanguarda", imageUrl: "https://i.imgur.com/NHGe1dM.png", description: "Um design único que desafia a norma." },
    { id: 113, name: "Cronarca", category: "Vanguarda", imageUrl: "https://i.imgur.com/21DJumn.png", description: "O governante do contínuo temporal." },
    { id: 114, name: "Constructo", category: "Estruturais", imageUrl: "https://i.imgur.com/WqJZ9sO.png", description: "A arquitetura do tempo em exibição." },
    { id: 115, name: "Decano", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/CkU6oNl.png", description: "A sabedoria do design clássico." },
    { id: 116, name: "Solstice", category: "Vanguarda", imageUrl: "https://i.imgur.com/XOQJQ6b.png", description: "O ponto de viragem no design do tempo." },
    { id: 117, name: "Engrenagem", category: "Estruturais", imageUrl: "https://i.imgur.com/mfIveOl.png", description: "O coração mecânico do tempo." },
    { id: 118, name: "Patrono", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/YnB3rqb.png", description: "A proteção da elegância atemporal." },
    { id: 119, name: "Cidadela", category: "Estruturais", imageUrl: "https://i.imgur.com/W7cSxSU.png", description: "Uma fortaleza de tempo e design." },
    { id: 120, name: "Legado II", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/GD0t6t5.png", description: "A herança do tempo, aprimorada." },
    { id: 121, name: "Nebulosa", category: "Vanguarda", imageUrl: "https://i.imgur.com/WHdRDqj.png", description: "O nascimento de uma estrela no seu pulso." },
    { id: 122, name: "Arcabouço", category: "Estruturais", imageUrl: "https://i.imgur.com/n1DaDmi.png", description: "A essência da engenharia revelada." },
    { id: 123, name: "Ateneu", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/3b4Oz4z.png", description: "O epicentro do conhecimento e da elegância." },
    { id: 124, name: "Elemento", category: "Estruturais", imageUrl: "https://i.imgur.com/rwpEaaz.png", description: "A forma pura da matéria e do tempo." },
    { id: 125, name: "Cronógrafo", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/265mnmt.png", description: "A precisão da medição clássica." },
    { id: 126, name: "Lúmen", category: "Vanguarda", imageUrl: "https://i.imgur.com/221PojI.png", description: "A luz que guia através do tempo." },
    { id: 127, name: "Armadura", category: "Estruturais", imageUrl: "https://i.imgur.com/Sb2BfvF.png", description: "Proteção e design em uma forma robusta." },
    { id: 128, name: "Santuário", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/474PsGx.png", description: "Um refúgio de elegância atemporal." },
    { id: 129, name: "Cronos", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/lWdkynm.png", description: "A personificação do tempo, em um design clássico." },
    { id: 130, name: "Mecânica", category: "Estruturais", imageUrl: "https://i.imgur.com/8OmIPkG.png", description: "A beleza da engenharia em sua forma mais pura." },
    { id: 131, name: "Estrela", category: "Vanguarda", imageUrl: "https://i.imgur.com/doCQ4zI.png", description: "Um ponto de luz na imensidão do tempo." },
    { id: 132, name: "Códice", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/V2Zq6Ir.png", description: "Os segredos do tempo, escritos em aço." },
    { id: 133, name: "Colmeia", category: "Estruturais", imageUrl: "https://i.imgur.com/fULQJPV.png", description: "A complexidade organizada da natureza e do tempo." },
    { id: 134, name: "Prisma", category: "Vanguarda", imageUrl: "https://i.imgur.com/OiLXWbv.png", description: "Decompondo o tempo em todas as suas cores." },
    { id: 135, name: "Majestade", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/yZARI1s.png", description: "A realeza do design atemporal." },
    { id: 136, name: "Labirinto", category: "Estruturais", imageUrl: "https://i.imgur.com/tlW61dr.png", description: "Perder-se na complexidade do tempo." },
    { id: 137, name: "Vetor", category: "Vanguarda", imageUrl: "https://i.imgur.com/cyzc6u1.png", description: "A direção e o sentido do futuro." },
    { id: 138, name: "Bastilha", category: "Estruturais", imageUrl: "https://i.imgur.com/Wv6PJfb.png", description: "Uma fortaleza impenetrável de precisão." },
    { id: 139, name: "Nebulosa II", category: "Vanguarda", imageUrl: "https://i.imgur.com/urNn3ZG.png", description: "A beleza cósmica em uma nova forma." },
    { id: 140, name: "Engrenagem II", category: "Estruturais", imageUrl: "https://i.imgur.com/ku6GLtg.png", description: "A evolução da mecânica do tempo." },
    { id: 141, name: "Nobreza", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/z1TcsrP.png", description: "Distinção e classe em cada detalhe." },
    { id: 142, name: "Singularidade II", category: "Vanguarda", imageUrl: "https://i.imgur.com/A40wbj5.png", description: "O ponto de viragem do design temporal." },
    { id: 143, name: "Mecanismo II", category: "Estruturais", imageUrl: "https://i.imgur.com/8V8P1xI.png", description: "A alma da máquina, agora mais exposta." },
    { id: 144, name: "Virtuoso II", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/0PdzHOW.png", description: "A maestria aprimorada para uma nova era." },
    { id: 145, name: "Cosmos II", category: "Vanguarda", imageUrl: "https://i.imgur.com/xSlQUd2.png", description: "Expandindo o universo em seu pulso." },
    { id: 146, name: "Cortex II", category: "Estruturais", imageUrl: "https://i.imgur.com/H1sCUcB.png", description: "A evolução da inteligência do design." },
    { id: 147, name: "Legado III", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/xw7ZD3d.png", description: "A herança do tempo, redefinida." },
    { id: 148, name: "Paradoxo II", category: "Vanguarda", imageUrl: "https://i.imgur.com/I0rwfBq.png", description: "A contradição que se torna perfeição." },
    { id: 149, name: "Matriz II", category: "Estruturais", imageUrl: "https://i.imgur.com/wRcbi2U.png", description: "A estrutura fundamental, evoluída." },
    { id: 150, name: "Singularidade III", category: "Vanguarda", imageUrl: "https://i.imgur.com/l4LyqIp.png", description: "A redefinição do ponto de viragem temporal." },
    { id: 151, name: "Legado IV", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/HR8j4nN.png", description: "A herança do tempo, elevada à perfeição." },
    { id: 152, name: "Cripto II", category: "Vanguarda", imageUrl: "https://i.imgur.com/WfnhUfY.png", description: "A evolução do tempo enigmático." },
    { id: 153, name: "Elementar", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/AdiR1x4.png", description: "A pureza da forma, a essência do tempo." },
    { id: 154, name: "Cronosfera II", category: "Vanguarda", imageUrl: "https://i.imgur.com/lxZXgTu.png", description: "A esfera do tempo, agora mais complexa e reveladora." },
    { id: 155, name: "Bastilha II", category: "Estruturais", imageUrl: "https://i.imgur.com/L0aulBv.png", description: "A fortaleza da precisão, reconstruída." },
    { id: 156, name: "Magnus II", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/Y0clStR.png", description: "A grandeza do design, aprimorada." },
    { id: 157, name: "Preceptor", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/sIejFss.png", description: "O guia do tempo, em forma clássica." },
    { id: 158, name: "Singularidade IV", category: "Vanguarda", imageUrl: "https://i.imgur.com/84Cbst3.png", description: "A redefinição final do ponto de colapso do tempo." },
    { id: 159, name: "Mecânica II", category: "Estruturais", imageUrl: "https://i.imgur.com/Dw0NzAQ.png", description: "A beleza da engenharia, agora mais complexa." },
    { id: 160, name: "Legado V", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/Hl8by5t.png", description: "A quintessência da herança horológica." },
    { id: 161, name: "Anomalia", category: "Vanguarda", imageUrl: "https://i.imgur.com/tUJmB6B.png", description: "Uma quebra nas leis do design convencional." },
    { id: 162, name: "Vértice II", category: "Estruturais", imageUrl: "https://i.imgur.com/EmJ8ZQf.png", description: "Elevando o ponto mais alto da engenharia." },
    { id: 163, name: "Artífice", category: "Estruturais", imageUrl: "https://i.imgur.com/qVelLq2.png", description: "A arte da criação do tempo, revelada." },
    { id: 164, name: "Soberano II", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/uqgK0EI.png", description: "A realeza do tempo, em uma nova era." },
    { id: 165, name: "Paradoxo III", category: "Vanguarda", imageUrl: "https://i.imgur.com/hMASosa.png", description: "A contradição que eleva a perfeição." },
    { id: 166, name: "Leviatã II", category: "Estruturais", imageUrl: "https://i.imgur.com/dNMtPqs.png", description: "A força monumental, agora mais revelada." },
    { id: 167, name: "Legado VI", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/7ZiOu3e.png", description: "A herança do tempo, para a eternidade." },
    { id: 168, name: "Singularidade V", category: "Vanguarda", imageUrl: "https://i.imgur.com/Fmcp7Y2.png", description: "O colapso do tempo em uma nova forma." },
    { id: 169, name: "Mecanismo III", category: "Estruturais", imageUrl: "https://i.imgur.com/1ysUZ1b.png", description: "A alma da máquina, em sua forma final." },
    { id: 170, name: "Virtuoso III", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/ZTyHJVV.png", description: "A maestria que transcende gerações." },
    { id: 171, name: "Cosmos III", category: "Vanguarda", imageUrl: "https://i.imgur.com/UzWL0Gs.png", description: "O universo em expansão no seu pulso." },
    { id: 172, name: "Evolução", category: "Vanguarda", imageUrl: "https://i.imgur.com/dx7SUHB.png", description: "O próximo passo na cronometria." },
    { id: 173, name: "Arcano II", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/j81B5DT.png", description: "Os segredos do tempo, com um toque clássico." },
    { id: 174, name: "Engrama II", category: "Estruturais", imageUrl: "https://i.imgur.com/8OBShON.png", description: "A memória do tempo, em uma nova forma." },
    { id: 176, name: "Lúmen II", category: "Vanguarda", imageUrl: "https://i.imgur.com/R5AMmYI.png", description: "A luz do tempo, em sua forma mais pura." },
    { id: 178, name: "Legado VII", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/PVttPUh.png", description: "A herança atemporal, redefinida." },
    { id: 179, name: "Singularidade VI", category: "Vanguarda", imageUrl: "https://i.imgur.com/TpgfExu.png", description: "O tempo colapsando em uma nova forma de arte." },
    { id: 180, name: "Mecanismo IV", category: "Estruturais", imageUrl: "https://i.imgur.com/gd7r5R2.png", description: "A alma da máquina, em sua forma mais pura." },
    { id: 181, name: "Arcabouço II", category: "Estruturais", imageUrl: "https://i.imgur.com/kgfB6j7.png", description: "A evolução da essência da engenharia." },
    { id: 182, name: "Legado VIII", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/qWasDvl.png", description: "A herança do tempo, para o futuro." },
    { id: 183, name: "Vetor II", category: "Vanguarda", imageUrl: "https://i.imgur.com/H5aqBiy.png", description: "A direção do futuro, em uma nova forma." },
    { id: 184, name: "Fractal II", category: "Estruturais", imageUrl: "https://i.imgur.com/AzESTDW.png", description: "A geometria infinita do tempo, evoluída." },
    { id: 185, name: "Singularidade VII", category: "Vanguarda", imageUrl: "https://i.imgur.com/JOuYsl4.png", description: "O ponto de colapso do tempo, redefinido." },
    { id: 186, name: "Cronosfera III", category: "Vanguarda", imageUrl: "https://i.imgur.com/1OWEyq2.png", description: "A esfera do tempo, em sua forma mais complexa." },
    { id: 187, name: "Mecanismo V", category: "Estruturais", imageUrl: "https://i.imgur.com/bvOq9WW.png", description: "A alma da máquina, em sua glória final." },
    { id: 188, name: "Virtuoso IV", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/2QDUyYN.png", description: "A maestria do tempo, em uma nova dimensão." },
    { id: 189, name: "Nexo II", category: "Vanguarda", imageUrl: "https://i.imgur.com/v82Gr0v.png", description: "A evolução da conexão entre forma e função." },
    { id: 190, name: "Cronógrafo II", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/zwAhmSv.png", description: "A precisão da medição, elevada a um novo patamar." },
    { id: 191, name: "Santuário II", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/1vf3n2y.png", description: "Um refúgio de elegância, aprimorado." },
    { id: 192, name: "Cidadela II", category: "Estruturais", imageUrl: "https://i.imgur.com/Scf4lHq.png", description: "A fortaleza do tempo, em uma nova forma." },
    { id: 193, name: "Evolução II", category: "Vanguarda", imageUrl: "https://i.imgur.com/26a1rpU.png", description: "O futuro da cronometria, em uma nova dimensão." },
    { id: 194, name: "Constructo II", category: "Estruturais", imageUrl: "https://i.imgur.com/fW6xjCl.png", description: "A arquitetura do tempo, em uma nova forma." },
    { id: 195, name: "Ateneu II", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/Bz14N5I.png", description: "O epicentro da elegância, aprimorado." },
    { id: 196, name: "Singularidade VIII", category: "Vanguarda", imageUrl: "https://i.imgur.com/Wg5XQbj.png", description: "O colapso do tempo, em uma nova dimensão." },
    { id: 197, name: "Bastilha III", category: "Estruturais", imageUrl: "https://i.imgur.com/qOyOWpd.png", description: "A fortaleza da precisão, em uma nova dimensão." },
    { id: 198, name: "Legado IX", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/hu0chTz.png", description: "A herança do tempo, em sua forma mais pura." },
    { id: 199, name: "Singularidade IX", category: "Vanguarda", imageUrl: "https://i.imgur.com/399Jw60.png", description: "O colapso do tempo, em uma nova forma de arte." },
    { id: 200, name: "Mecanismo VI", category: "Estruturais", imageUrl: "https://i.imgur.com/IhUXbWn.png", description: "A alma da máquina, em sua forma mais complexa." },
    { id: 201, name: "Virtuoso V", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/4wMfs2q.png", description: "A maestria do tempo, em sua glória final." },
    { id: 202, name: "Cronosfera IV", category: "Vanguarda", imageUrl: "https://i.imgur.com/hxusrZG.png", description: "A esfera do tempo, em sua forma mais pura." },
    { id: 204, name: "Legado X", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/JrwYbj4.png", description: "A herança do tempo, em sua forma final." },
    { id: 205, name: "Singularidade X", category: "Vanguarda", imageUrl: "https://i.imgur.com/Ak5CqqQ.png", description: "O colapso do tempo, em uma nova era." },
    { id: 207, name: "Caos", category: "Vanguarda", imageUrl: "https://i.imgur.com/IBE3stV.png", description: "A beleza do caos, organizada em um pulso." },
    { id: 208, name: "Singularidade XI", category: "Vanguarda", imageUrl: "https://i.imgur.com/xZlp3Q6.png", description: "A singularidade do tempo, em uma nova forma." },
    { id: 209, name: "Legado XI", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/JTF9ZkT.png", description: "A herança do tempo, em sua forma mais pura." },
    { id: 210, name: "Arcabouço III", category: "Estruturais", imageUrl: "https://i.imgur.com/rcMKC6B.png", description: "A essência da engenharia, em uma nova forma." },
    { id: 211, name: "Legado XII", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/mylfVug.png", description: "A herança do tempo, em sua forma mais pura." },
    { id: 212, name: "Singularidade XII", category: "Vanguarda", imageUrl: "https://i.imgur.com/btWvXcd.png", description: "O colapso do tempo, em uma nova dimensão." },
    { id: 213, name: "Arcabouço IV", category: "Estruturais", imageUrl: "https://i.imgur.com/9eVsRyj.png", description: "A essência da engenharia, em uma nova dimensão." },
    { id: 214, name: "Legado XIII", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/Dvp81yx.png", description: "A herança do tempo, em sua forma mais pura." },
    { id: 215, name: "Cripto III", category: "Vanguarda", imageUrl: "https://i.imgur.com/YgpJeQy.png", description: "A evolução final do tempo enigmático." },
    { id: 216, name: "Armadura II", category: "Estruturais", imageUrl: "https://i.imgur.com/hAOtHEu.png", description: "A proteção e o design, em uma nova forma." },
    { id: 217, name: "Códice II", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/pGK5A2S.png", description: "Os segredos do tempo, reescritos." },
    { id: 218, name: "Singularidade XIII", category: "Vanguarda", imageUrl: "https://i.imgur.com/w4yoBjM.png", description: "O ponto de colapso do tempo, em uma nova era." },
    { id: 219, name: "Mecanismo VIII", category: "Estruturais", imageUrl: "https://i.imgur.com/d6i8SRG.png", description: "A alma da máquina, em sua forma mais pura." },
    { id: 220, name: "Legado XIV", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/jzAuLBY.png", description: "A herança do tempo, em sua forma mais nobre." },
    { id: 221, name: "Singularidade XIV", category: "Vanguarda", imageUrl: "https://i.imgur.com/UQjpnlH.png", description: "O colapso do tempo, em uma nova era de design." },
    { id: 222, name: "Mecanismo IX", category: "Estruturais", imageUrl: "https://i.imgur.com/DmDkFKH.png", description: "A alma da máquina, em sua forma mais complexa." },
    { id: 223, name: "Entropia", category: "Vanguarda", imageUrl: "https://i.imgur.com/TEeKKz1.png", description: "A ordem emergindo do caos do tempo." },
    { id: 224, name: "Armadura III", category: "Estruturais", imageUrl: "https://i.imgur.com/SUDkWhb.png", description: "A evolução final da proteção e do design." },
    { id: 225, name: "Códice III", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/dQzfUeZ.png", description: "A revelação final dos segredos do tempo." },
    { id: 226, name: "Singularidade XV", category: "Vanguarda", imageUrl: "https://i.imgur.com/PQXUg4w.png", description: "O tempo em sua forma mais pura e singular." },
    { id: 227, name: "Mecanismo X", category: "Estruturais", imageUrl: "https://i.imgur.com/pDQFdc5.png", description: "A alma da máquina, em sua forma mais complexa." },
    { id: 228, name: "Virtuoso VI", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/S74opRh.png", description: "A maestria do tempo, em sua forma mais pura." },
    { id: 229, name: "Cronosfera V", category: "Vanguarda", imageUrl: "https://i.imgur.com/dAgc5y3.png", description: "A esfera do tempo, em sua forma mais complexa." },
    { id: 230, name: "Constructo III", category: "Estruturais", imageUrl: "https://i.imgur.com/h0Vosde.png", description: "A arquitetura do tempo, em sua forma mais pura." },
    { id: 231, name: "Ateneu III", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/db4j2U5.png", description: "O epicentro da elegância, em sua forma final." },
    { id: 232, name: "Singularidade XVI", category: "Vanguarda", imageUrl: "https://i.imgur.com/UgrzSzz.png", description: "O colapso do tempo, em uma nova dimensão." },
    { id: 233, name: "Arcabouço V", category: "Estruturais", imageUrl: "https://i.imgur.com/j8w7sGJ.png", description: "A essência da engenharia, em sua forma mais pura." },
    { id: 234, name: "Legado XIV", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/5vQjGsG.png", description: "A herança do tempo, em uma nova dimensão." },
    { id: 235, name: "Nexo III", category: "Estruturais", imageUrl: "https://i.imgur.com/W3NZ8GW.png", description: "A conexão final entre a forma e a função." },
    { id: 236, name: "Cronógrafo III", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/OJ8hTK4.png", description: "A precisão da medição, em sua forma mais pura." },
    { id: 237, name: "Evolução III", category: "Vanguarda", imageUrl: "https://i.imgur.com/gg5kbXm.png", description: "O futuro da cronometria, em uma nova dimensão." },
    { id: 238, name: "Constructo IV", category: "Estruturais", imageUrl: "https://i.imgur.com/MR1B9wb.png", description: "A arquitetura do tempo, em sua forma mais complexa." },
    { id: 239, name: "Ateneu III", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/j7CqgMh.png", description: "O epicentro da elegância, em sua forma final." },
    { id: 240, name: "Singularidade XV", category: "Vanguarda", imageUrl: "https://i.imgur.com/MLy6xKH.png", description: "O colapso do tempo, em uma nova dimensão." },
    { id: 241, name: "Bastilha IV", category: "Estruturais", imageUrl: "https://i.imgur.com/sb2r7MH.png", description: "A fortaleza da precisão, em sua forma final." },
    { id: 242, name: "Legado XV", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/Czxx7ur.png", description: "A herança do tempo, em sua forma mais pura." },
    { id: 243, name: "Singularidade XVI", category: "Vanguarda", imageUrl: "https://i.imgur.com/li5WoDd.png", description: "O colapso do tempo, em uma nova forma de arte." },
    { id: 244, name: "Nexo IV", category: "Estruturais", imageUrl: "https://i.imgur.com/APBHWJ4.png", description: "A conexão final, redefinida." },
    { id: 245, name: "Cronógrafo IV", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/WJN6Glj.png", description: "A precisão da medição, em sua forma final." },
    { id: 246, name: "Evolução IV", category: "Vanguarda", imageUrl: "https://i.imgur.com/VvjwtU2.png", description: "O futuro da cronometria, em uma nova era." },
    { id: 247, name: "Constructo V", category: "Estruturais", imageUrl: "https://i.imgur.com/P09YRWx.png", description: "A arquitetura do tempo, em sua forma mais pura." },
    { id: 248, name: "Ateneu IV", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/O0xaNoi.png", description: "O epicentro da elegância, em sua glória final." },
    { id: 249, name: "Singularidade XVII", category: "Vanguarda", imageUrl: "https://i.imgur.com/0DOgBG1.png", description: "O colapso do tempo, em uma nova dimensão." },
    { id: 250, name: "Bastilha V", category: "Estruturais", imageUrl: "https://i.imgur.com/5cyPO98.png", description: "A fortaleza da precisão, em sua forma mais pura." },
    { id: 251, name: "Legado XVI", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/odO1sYt.png", description: "A herança do tempo, em sua glória final." },
    { id: 252, name: "Singularidade XVIII", category: "Vanguarda", imageUrl: "https://i.imgur.com/VkzCCtE.png", description: "O colapso do tempo, em uma nova forma de arte." },
    { id: 253, name: "Mecanismo XI", category: "Estruturais", imageUrl: "https://i.imgur.com/Rm2ja11.png", description: "A alma da máquina, em sua forma mais complexa." },
    { id: 254, name: "Virtuoso VII", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/cyCJRLa.png", description: "A maestria do tempo, em sua glória final." },
    { id: 255, name: "Cronosfera VI", category: "Vanguarda", imageUrl: "https://i.imgur.com/AWaDdfA.png", description: "A esfera do tempo, em sua forma mais pura." },
    { id: 256, name: "Arcabouço VI", category: "Estruturais", imageUrl: "https://i.imgur.com/bWjNsws.png", description: "A essência da engenharia, em sua forma mais complexa." },
    { id: 257, name: "Legado XVII", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/ine9azp.png", description: "A herança do tempo, em sua forma final." },
    { id: 258, name: "Singularidade XIX", category: "Vanguarda", imageUrl: "https://i.imgur.com/h7pddaJ.png", description: "O colapso do tempo, em uma nova era." },
    { id: 259, name: "Mecanismo XII", category: "Estruturais", imageUrl: "https://i.imgur.com/Pa5yBy3.png", description: "A alma da máquina, em sua forma mais complexa." },
    { id: 260, name: "Virtuoso VIII", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/xjB0kVm.png", description: "A maestria do tempo, em sua forma mais pura." },
    { id: 261, name: "Cronosfera VII", category: "Vanguarda", imageUrl: "https://i.imgur.com/BD7l6Rr.png", description: "A esfera do tempo, em sua forma mais complexa." },
    { id: 262, name: "Singularidade XX", category: "Vanguarda", imageUrl: "https://i.imgur.com/UDST4DH.png", description: "A anomalia do tempo, em uma nova dimensão." },
    { id: 263, name: "Virtuoso IX", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/wkmkwJD.png", description: "A maestria do tempo, em sua forma mais nobre." },
    { id: 264, name: "Mecanismo XIII", category: "Estruturais", imageUrl: "https://i.imgur.com/o2bOC7E.png", description: "A alma da máquina, em sua forma mais complexa." },
    { id: 265, name: "Paradoxo IV", category: "Vanguarda", imageUrl: "https://i.imgur.com/j4PLQS9.png", description: "A contradição que se torna a perfeição final." },
    { id: 266, name: "Legado XVIII", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/fv5pokn.png", description: "A herança do tempo, em sua glória eterna." },
    { id: 267, name: "Constructo VI", category: "Estruturais", imageUrl: "https://i.imgur.com/y1c3WGS.png", description: "A arquitetura do tempo, em sua forma mais pura." },
    { id: 268, name: "Cronosfera VIII", category: "Vanguarda", imageUrl: "https://i.imgur.com/0cCGkVj.png", description: "A esfera do tempo, em uma nova dimensão." },
    { id: 269, name: "Arcabouço VII", category: "Estruturais", imageUrl: "https://i.imgur.com/g1wpNi3.png", description: "A essência da engenharia, em sua forma mais complexa." },
    { id: 270, name: "Soberano III", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/jldtNkA.png", description: "A realeza do tempo, em uma nova era de design." },
    { id: 271, name: "Quimera II", category: "Vanguarda", imageUrl: "https://i.imgur.com/ZZdXKop.png", description: "A fusão mítica, evoluída para o futuro." },
    { id: 272, name: "Singularidade XXI", category: "Vanguarda", imageUrl: "https://i.imgur.com/7YUYhTX.png", description: "A nova fronteira do design temporal, onde a complexidade encontra a clareza." },
    { id: 273, name: "Legado XIX", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/fa9uiql.png", description: "A tradição encontra a modernidade em uma harmonia perfeita de forma e função." },
    { id: 274, name: "Mecanismo XIV", category: "Estruturais", imageUrl: "https://i.imgur.com/W4LP1ho.png", description: "A beleza da engenharia exposta em sua forma mais crua e fascinante." },
    { id: 275, name: "Paradoxo V", category: "Vanguarda", imageUrl: "https://i.imgur.com/nwJnFZF.png", description: "Desafiando as convenções, este relógio reescreve as regras do tempo." },
    { id: 276, name: "Noctua", category: "Vanguarda", imageUrl: "https://i.imgur.com/EdRjaHj.png", description: "A escuridão revela a verdadeira face do tempo." },
    { id: 277, name: "Legado XX", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/z61Ckhk.png", description: "Onde a tradição encontra a transparência do futuro." },
    { id: 278, name: "Sinfonia Mecânica", category: "Estruturais", imageUrl: "https://i.imgur.com/tXWT94r.png", description: "Cada componente, uma nota na orquestra do tempo." },
    { id: 279, name: "Singularidade XXII", category: "Vanguarda", imageUrl: "https://i.imgur.com/vT8whXo.png", description: "Quebrando as barreiras da forma e do tempo." },
    { id: 280, name: "Embaixador", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/6uP22RY.png", description: "A diplomacia da elegância em cada segundo." },
    { id: 281, name: "Arcabouço VIII", category: "Estruturais", imageUrl: "https://i.imgur.com/IZuSiFZ.png", description: "A beleza da engenharia, despojada ao essencial." },
    { id: 282, name: "Horizonte II", category: "Vanguarda", imageUrl: "https://i.imgur.com/Xq8J86U.png", description: "Expandindo os limites do que é possível em um pulso." },
    { id: 283, name: "Consulado", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/QwL94n6.png", description: "A autoridade do design atemporal, com um toque de complexidade." },
    { id: 284, name: "Mecanismo XV", category: "Estruturais", imageUrl: "https://i.imgur.com/Mt9nH4t.png", description: "A alma da máquina, em sua forma mais intrincada." },
    { id: 285, name: "Ecos Temporais", category: "Vanguarda", imageUrl: "https://i.imgur.com/sN7SWxH.png", description: "O futuro sussurra em ecos de luz e sombra." },
    { id: 286, name: "Singularidade XXIII", category: "Vanguarda", imageUrl: "https://i.imgur.com/HTcrOGb.png", description: "A convergência de realidades, onde o tempo se dobra sobre si mesmo." },
    { id: 287, name: "Legado XXI", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/sGe19df.png", description: "A herança da relojoaria clássica, revelada através de uma nova perspectiva." },
    { id: 288, name: "Mecanismo XVI", category: "Estruturais", imageUrl: "https://i.imgur.com/bqpSC4v.png", description: "A sinfonia da engenharia, onde cada engrenagem conta uma parte da história do tempo." },
    { id: 289, name: "Nébula III", category: "Vanguarda", imageUrl: "https://i.imgur.com/xslFADb.png", description: "Uma janela para o cosmos, capturando a beleza caótica de uma nebulosa estelar." },
    { id: 290, name: "Virtuoso X", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/O7ejkHa.png", description: "A maestria da relojoaria, exibida com uma elegância que transcende o tempo." },
    { id: 291, name: "Quimera III", category: "Vanguarda", imageUrl: "https://i.imgur.com/x3k4VLe.png", description: "Uma fusão impossível de biologia e mecânica, dando vida a uma nova forma de medir o tempo." },
    { id: 292, name: "Reator II", category: "Estruturais", imageUrl: "https://i.imgur.com/cfz7pQD.png", description: "O núcleo pulsante da inovação, onde a energia do tempo é liberada." },
    { id: 293, name: "Soberano IV", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/cgUB0UP.png", description: "A majestade do design clássico, com a alma do mecanismo orgulhosamente exposta." },
    { id: 294, name: "Ocular II", category: "Vanguarda", imageUrl: "https://i.imgur.com/BvVpe73.png", description: "O olho que tudo vê do tempo, observando o futuro a cada tique-taque." },
    { id: 295, name: "Cidadela III", category: "Estruturais", imageUrl: "https://i.imgur.com/D2obpuy.png", description: "Uma fortaleza de precisão, com cada detalhe construído para resistir à prova do tempo." },
    { id: 296, name: "Legado XXII", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/Y36wn6v.png", description: "A pureza do legado, onde a tradição se abre para revelar sua beleza interior." },
    { id: 297, name: "Cronomorfo", category: "Vanguarda", imageUrl: "https://i.imgur.com/ppmPM0P.png", description: "O tempo se dobra e se molda a uma nova forma de percepção." },
    { id: 298, name: "Legado XXIII", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/9qTVX0E.png", description: "A alma do tempo clássico, revelada em sua totalidade." },
    { id: 299, name: "Arcabouço IX", category: "Estruturais", imageUrl: "https://i.imgur.com/07npiAz.png", description: "A arquitetura do tempo, reduzida à sua mais pura e essencial estrutura." },
    { id: 300, name: "Quasar II", category: "Vanguarda", imageUrl: "https://i.imgur.com/8U2cFou.png", description: "Uma explosão de energia cósmica que redefine a leitura do tempo." },
    { id: 301, name: "Virtuoso XI", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/eBjm7hk.png", description: "A virtuosidade da alta relojoaria, despida de segredos." },
    { id: 302, name: "Mecanismo XVII", category: "Estruturais", imageUrl: "https://i.imgur.com/1tTJIRp.png", description: "A beleza bruta da engenharia, onde cada movimento é uma obra de arte." },
    { id: 303, name: "Paradigma II", category: "Vanguarda", imageUrl: "https://i.imgur.com/pakalcp.png", description: "Quebrando os moldes da tradição para criar um novo padrão de tempo." },
    { id: 304, name: "Soberano V", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/3936xaJ.png", description: "A majestade do tempo clássico com o coração aberto para o futuro." },
    { id: 305, name: "Estratos Temporais", category: "Estruturais", imageUrl: "https://i.imgur.com/u6jOKYO.png", description: "As camadas do tempo, sobrepostas em uma arquitetura complexa." },
    { id: 306, name: "Biomorfose", category: "Vanguarda", imageUrl: "https://i.imgur.com/dLUTNt7.png", description: "O tempo como uma entidade orgânica, evoluindo a cada segundo." },
    { id: 307, name: "Legado XXIV", category: "Clássicos Reinventados", imageUrl: "https://i.imgur.com/LH1FSnx.png", description: "A harmonia perfeita entre a tradição atemporal e a complexidade moderna." }
];